from enum import Enum, unique


@unique
class Colorspace(str, Enum):
    RGB = "RGB"
    GRAY = "GRAY"


COLOR_LUT = {Colorspace.GRAY: "L", Colorspace.RGB: "RGB"}
PDF_EXT = ".pdf"
PIL_PNG = "PNG"
PNG_EXT = ".png"
MARKDOWN_EXT = ".md"
HTML_EXT = ".html"

INFERENCE_GROUP = "inference"
PREPROCESSING_GROUP = "preprocessing"
DETECT_PASSPORTS_TASKS = "detect-passports"
PREPROCESS_DOCS_TASK = "preprocess-docs"
CREATE_PREPROCESSING_TASKS_TASK = "create-preprocessing-tasks"

GOTENBERG_LIBREOFFICE_EXTS = {
    ".123",
    ".602",
    ".abw",
    ".bib",
    ".bmp",
    ".cdr",
    ".cgm",
    ".cmx",
    ".csv",
    ".cwk",
    ".dbf",
    ".dif",
    ".doc",
    ".docm",
    ".docx",
    ".dot",
    ".dotm",
    ".dotx",
    ".dxf",
    ".emf",
    ".eps",
    ".epub",
    ".fodg",
    ".fodp",
    ".fods",
    ".fodt",
    ".fopd",
    ".gif",
    ".htm",
    ".html",
    ".hwp",
    ".jpeg",
    ".jpg",
    ".key",
    ".ltx",
    ".lwp",
    ".mcw",
    ".met",
    ".mml",
    ".mw",
    ".numbers",
    ".odd",
    ".odg",
    ".odm",
    ".odp",
    ".ods",
    ".odt",
    ".otg",
    ".oth",
    ".otp",
    ".ots",
    ".ott",
    ".pages",
    ".pbm",
    ".pcd",
    ".pct",
    ".pcx",
    ".pdb",
    ".pdf",
    ".pgm",
    ".png",
    ".pot",
    ".potm",
    ".potx",
    ".ppm",
    ".pps",
    ".ppt",
    ".pptm",
    ".pptx",
    ".psd",
    ".psw",
    ".pub",
    ".pwp",
    ".pxl",
    ".ras",
    ".rtf",
    ".sda",
    ".sdc",
    ".sdd",
    ".sdp",
    ".sdw",
    ".sgl",
    ".slk",
    ".smf",
    ".stc",
    ".std",
    ".sti",
    ".stw",
    ".svg",
    ".svm",
    ".swf",
    ".sxc",
    ".sxd",
    ".sxg",
    ".sxi",
    ".sxm",
    ".sxw",
    ".tga",
    ".tif",
    ".tiff",
    ".txt",
    ".uof",
    ".uop",
    ".uos",
    ".uot",
    ".vdx",
    ".vor",
    ".vsd",
    ".vsdm",
    ".vsdx",
    ".wb2",
    ".wk1",
    ".wks",
    ".wmf",
    ".wpd",
    ".wpg",
    ".wps",
    ".xbm",
    ".xhtml",
    ".xls",
    ".xlsb",
    ".xlsm",
    ".xlsx",
    ".xlt",
    ".xltm",
    ".xltx",
    ".xlw",
    ".xml",
    ".xpm",
    ".zabw",
}

GOTENBERG_SUPPORTED_EXTS = set(GOTENBERG_LIBREOFFICE_EXTS)
GOTENBERG_SUPPORTED_EXTS.remove(PDF_EXT)
GOTENBERG_SUPPORTED_EXTS.add(HTML_EXT)
GOTENBERG_SUPPORTED_EXTS.add(MARKDOWN_EXT)
